// <auto-generated />
using System;
using Mangak_System._1_DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaK_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730151623_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.CategorySeries", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("CategorySeries");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.PublishingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DecidedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DecidedById");

                    b.HasIndex("SeriesId")
                        .IsUnique();

                    b.ToTable("PublishingSchedules");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFilePublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReviewedById");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Reader");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            Bio = "Handles account management.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin.mangak@gmail.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "System",
                            PasswordHash = "$2a$11$ulBAY43Pfpj.IP0WQIuFrOAm9ZmahfWnc.Ugybp4J8D67/CLniMC6",
                            Phone = "0902234506",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000000"),
                            Bio = "Handles account management.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "mangaksystem.admin@gmail.com",
                            FirstName = "Mangaka",
                            IsDeleted = false,
                            LastName = "System",
                            PasswordHash = "$2a$11$cLPq8siwUg2S5V4XNaiM8Oc6B1pe6BgB1gJdYHmUfgPkaODod1EIi",
                            Phone = "0865326785",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000000"),
                            Bio = "Oversees final approval and publication planning.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "board.mangak@gmail.com",
                            FirstName = "Editorial",
                            IsDeleted = false,
                            LastName = "Board",
                            PasswordHash = "$2a$11$z8YIdqtAEzYhflEdzA2BueXvvDhFkCrtQl2m.gN38c25UnQYsIyf.",
                            Phone = "0902234507",
                            Role = "Editorial",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("e24a52c3-96cb-4034-88db-4e1bba697841"),
                            Bio = "Official Tantou account.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tranmaiconghung@gmail.com",
                            FirstName = "Togoro",
                            IsDeleted = false,
                            LastName = "Mori",
                            PasswordHash = "$2a$11$wqkWTRk76JOZgoNgmeaJvutSNAGJAhIDX3eu/8cLWYbSVFoyObrdu",
                            Phone = "0901234567",
                            Role = "Tantou",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("f39b61d2-74ba-42a1-9a7c-3b0acc786520"),
                            Bio = "Fantasy editor and content quality.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "michael.anderson@gmail.com",
                            FirstName = "Mika",
                            IsDeleted = false,
                            LastName = "Ayashi",
                            PasswordHash = "$2a$11$k0aUHB80AaaAOoBnWAViwODti2AF4lKFw2JbsiBM/ucaYe9wnl.MS",
                            Phone = "0975633219",
                            Role = "Tantou",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000000"),
                            AuthorName = "Akira Koba",
                            Bio = "A versatile manga creator known for sci-fi adventures and immersive world-building.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "nhathanhthinguyen@gmail.com",
                            FirstName = "Akira",
                            IsDeleted = false,
                            LastName = "Kobayashi",
                            PasswordHash = "$2a$11$7N/oOICse8bsHRVjw0WiDejq8wFTicRnXEjhmBxd2N4Sl/Qco1pdC",
                            Phone = "0901234565",
                            Role = "Mangaka",
                            Status = "Active",
                            SupervisorId = new Guid("f39b61d2-74ba-42a1-9a7c-3b0acc786520")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000000"),
                            AuthorName = "Haru Sato",
                            Bio = "A manga artist specializing in action and adventure stories with dynamic illustrations.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "haruto.sato@gmail.com",
                            FirstName = "Haruto",
                            IsDeleted = false,
                            LastName = "Sato",
                            PasswordHash = "$2a$11$tZME3QovDc/3FI4oOx6uvu7tmMBYbhtaNYvYGq7TGJvVDo0oKCgxa",
                            Phone = "0901234561",
                            Role = "Mangaka",
                            Status = "Active",
                            SupervisorId = new Guid("f39b61d2-74ba-42a1-9a7c-3b0acc786520")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000000"),
                            AuthorName = "Ren Taka",
                            Bio = "Passionate about psychological mysteries and creating emotionally complex characters.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tuanle17082k5@gmail.com",
                            FirstName = "Ren",
                            IsDeleted = false,
                            LastName = "Takahashi",
                            PasswordHash = "$2a$11$Ubj63s7D/C9GGx6WDgbz5.iXipfT1iW1pauB11LavweRUvRyI3v6m",
                            Phone = "0901234562",
                            Role = "Mangaka",
                            Status = "Active",
                            SupervisorId = new Guid("f39b61d2-74ba-42a1-9a7c-3b0acc786520")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000000"),
                            AuthorName = "Yuki Naka",
                            Bio = "Creates heartwarming slice-of-life and romance manga inspired by everyday Japanese culture.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "yuki.nakamura@gmail.com",
                            FirstName = "Yuki",
                            IsDeleted = false,
                            LastName = "Nakamura",
                            PasswordHash = "$2a$11$QRutO6OZfCho8czGilByWuyRmRlQyxHSlGpZzP549OYToU2EjQeuG",
                            Phone = "0901234563",
                            Role = "Mangaka",
                            Status = "Active",
                            SupervisorId = new Guid("e24a52c3-96cb-4034-88db-4e1bba697841")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000000"),
                            AuthorName = "Kaito Fuji",
                            Bio = "Focuses on dark fantasy and supernatural worlds with highly detailed artwork.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "kaito.fujimoto@gmail.com",
                            FirstName = "Kaito",
                            IsDeleted = false,
                            LastName = "Fujimoto",
                            PasswordHash = "$2a$11$mivf3Nx71qxFZfi1bYt/Uu5IwYegHZXo8CI3oGES9yk2Wak20opLy",
                            Phone = "0901234564",
                            Role = "Mangaka",
                            Status = "Active",
                            SupervisorId = new Guid("e24a52c3-96cb-4034-88db-4e1bba697841")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000000"),
                            Bio = "Provides editorial support and assists with manga publication workflows.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "xuanhieubato@gmail.com",
                            FirstName = "Aoi",
                            IsDeleted = false,
                            LastName = "Yamamoto",
                            PasswordHash = "$2a$11$8tNqQlqdW.qWeSlHD9bxkOzpJNt/gvJEPuHZuaU5WyyA9VZE6doTq",
                            Phone = "0902234501",
                            Role = "Assistant",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000000"),
                            Bio = "Coordinates schedules and communicates with artists and publishers.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "daichi.mori@gmail.com",
                            FirstName = "Daichi",
                            IsDeleted = false,
                            LastName = "Mori",
                            PasswordHash = "$2a$11$N.wGhUp5lKhnoafvp3JwWuHXF/IY/MWi4LEl2aErxJ704/RAgGdUG",
                            Phone = "0902234502",
                            Role = "Assistant",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000000"),
                            Bio = "Helps manage manuscripts, deadlines, and project documentation.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "kimngan21102020@gmail.com",
                            FirstName = "Emi",
                            IsDeleted = false,
                            LastName = "Shimizu",
                            PasswordHash = "$2a$11$XbJQdZPicvuHm.igcqBBl.sDGAIjWi1ZX8m3qtxxBqDPICTAx4eui",
                            Phone = "0902234503",
                            Role = "Assistant",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000000"),
                            Bio = "Supports creative teams by organizing assets and tracking progress.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "riku.hayashi@gmail.com",
                            FirstName = "Riku",
                            IsDeleted = false,
                            LastName = "Hayashi",
                            PasswordHash = "$2a$11$ln7.kBOWVJ8qWYtppfT59.GiIjiLAmxwzH1iRkDA/AJ7rt8t5E8Dy",
                            Phone = "0902234504",
                            Role = "Assistant",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000000"),
                            Bio = "Assists with content reviews and communication between departments.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "nozomi.ishikawa@gmail.com",
                            FirstName = "Nozomi",
                            IsDeleted = false,
                            LastName = "Ishikawa",
                            PasswordHash = "$2a$11$j2ng4tXNrfVPDciPtZtBmuLE5OkzsqYLoFbThEjZu9JXaYvUoAq/q",
                            Phone = "0902234505",
                            Role = "Assistant",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000000"),
                            Bio = "Handles administrative tasks and ensures smooth production coordination.",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sora.okamoto@gmail.com",
                            FirstName = "Sora",
                            IsDeleted = false,
                            LastName = "Okamoto",
                            PasswordHash = "$2a$11$zpqD/2IVAzfYzhO1whgO8uui3rAjlAriQt7TuJtA9PCddG9zIANjm",
                            Phone = "0902234506",
                            Role = "Assistant",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.CategorySeries", b =>
                {
                    b.HasOne("Mangak_System._1_DAL.Entity.Category", "Category")
                        .WithMany("CategorySeries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mangak_System._1_DAL.Entity.Series", "Series")
                        .WithMany("CategorySeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Feedback", b =>
                {
                    b.HasOne("Mangak_System._1_DAL.Entity.User", "Sender")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mangak_System._1_DAL.Entity.Series", "Series")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.PublishingSchedule", b =>
                {
                    b.HasOne("Mangak_System._1_DAL.Entity.User", "DecidedBy")
                        .WithMany("PublishingSchedules")
                        .HasForeignKey("DecidedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mangak_System._1_DAL.Entity.Series", "Series")
                        .WithOne("PublishingSchedule")
                        .HasForeignKey("Mangak_System._1_DAL.Entity.PublishingSchedule", "SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedBy");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Series", b =>
                {
                    b.HasOne("Mangak_System._1_DAL.Entity.User", "ApprovedBy")
                        .WithMany("ApprovedSeries")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mangak_System._1_DAL.Entity.User", "CreatedBy")
                        .WithMany("CreatedSeries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mangak_System._1_DAL.Entity.User", "ReviewedBy")
                        .WithMany("ReviewedSeries")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.User", b =>
                {
                    b.HasOne("Mangak_System._1_DAL.Entity.User", "Supervisor")
                        .WithMany("Mangakas")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Category", b =>
                {
                    b.Navigation("CategorySeries");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.Series", b =>
                {
                    b.Navigation("CategorySeries");

                    b.Navigation("Feedbacks");

                    b.Navigation("PublishingSchedule");
                });

            modelBuilder.Entity("Mangak_System._1_DAL.Entity.User", b =>
                {
                    b.Navigation("ApprovedSeries");

                    b.Navigation("CreatedSeries");

                    b.Navigation("Feedbacks");

                    b.Navigation("Mangakas");

                    b.Navigation("PublishingSchedules");

                    b.Navigation("ReviewedSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
